; PlatformIO Project Configuration
; 868 MHz Weather Station Raw Sniffer (ESP32-S3 + CC1101)

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM12
monitor_port = COM12

; Flash mode for ESP32-S3
board_build.flash_mode = dio
board_build.mcu = esp32s3

lib_deps =
    knolleary/PubSubClient@^2.8